import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import FeedbackHubSiteimprove_properties from "./FeedbackHubSiteimprove_properties";

/**
 * Overrides of ResourceBundle "FeedbackHubSiteimprove" for Locale "de".
 * @see FeedbackHubSiteimprove_properties#INSTANCE
 */
ResourceBundleUtil.override(FeedbackHubSiteimprove_properties, {
  siteimprove_scoreDetails: "Bewertungsdetails",
  siteimprove_scoreDifferences: "Unterschiede",
  siteimprove_overallScore: "Generelle Bewertung",
  siteimprove_digitalCertaintyIndex: "Digital Certainty Index",
  siteimprove_preview_tab_title: "Vorschau",
  siteimprove_comparison_tab_title: "Vergleich",
  siteimprove_comparison_tab_tooltip: "Vergleich von Preview und Live Seite",
  siteimprove_points: "Punkte",
  siteimprove_title: "Siteimprove",
  siteimprove_content_quality: "Content Qualität",
  siteimprove_a11y: "Barrierefreiheit",
  siteimprove_seo_issues: "SEO Bewertung",
  siteimprove_seo: "SEO",
  siteimprove_quality: "Qualitätssicherung",
  siteimprove_issue_link: "Klicken Sie hier um alle Probleme in Siteimprove zu sehen",
  siteimprove_preview_site: "Vorschau",
  siteimprove_preview_site_link: "Preview öffnen",
  siteimprove_live_site: "Live Seite",
  siteimprove_live_site_link: "Live Site öffnen",
  siteimprove_gain_score: "Sie <b>gewinnen {0} Punkte<\/b> mit den aktuellen Änderungen.",
  siteimprove_lose_score: "Sie <b>verlieren {0} Punkte<\/b> mit den aktuellen Änderungen.",
  siteimprove_last_crawl: "Letzte Prüfung:",
  siteimprove_checking: "Inhalt wird geprüft...",
  siteimprove_unknown: "unbekannt",
  siteimprove_issues_help: "Beheben Sie diese Probleme um die Bewertung zu verbessern.",
  siteimprove_issue: "Problem",
  siteimprove_category: "Kategorie",
  siteimprove_points_to_gain: "zusätzliche Punkte",
  siteimprove_filter: "Filter:",
  siteimprove_issues_all: "Alle",
  siteimprove_issues_a11y: "Barrierefreiheit",
  siteimprove_issues_a11y_count: "Probleme Barrierefreiheit ({0})",
  siteimprove_issue_category_accessibility: "Accessibility",
  siteimprove_issues_qa: "Qualitätssicherung",
  siteimprove_issues_qa_count: "Probleme Qualitätssicherung ({0})",
  siteimprove_issue_category_content: "Qualitätssicherung",
  siteimprove_issues_seo: "SEO",
  siteimprove_issue_category_seov2: "SEO",
  siteimprove_issues_seo_count: "SEO Fehler ({0}):",
  siteimprove_issues_seo_content: "Inhalt",
  siteimprove_issues_seo_technical: "Technisch",
  siteimprove_error_EMAIL_NOT_SET: "Bitte geben Sie einen gültige Emailadresse in der Konfiguration für {0} an.",
  siteimprove_error_API_KEY_NOT_SET: "Bitte geben Sie einen gültigen apiKey in der Konfiguration für {0} an.",
  siteimprove_error_REST_ERROR: "Siteimprove hat einen Fehler gemeldet: {1}",
  siteimprove_error_NO_CONTENT_METATAG_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_NO_CONTENT_METATAG_WITH_CONTENT_ID_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_NO_CONTENT_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_live_NO_CONTENT_METATAG_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_live_NO_CONTENT_METATAG_WITH_CONTENT_ID_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_live_NO_CONTENT_FOUND: "Keine Information zum aktuellen Inhalt gefunden. Bitte stellen Sie sicher, dass Siteimprove ihn crawled.",
  siteimprove_error_live_NOT_PUBLISHED: "Der Inhalt ist nicht veröffentlicht. Publizieren Sie den Inhalt, um Siteimprove Ergebnisse zu bekommen.",
  recrawl_preview_page_btn_text: "Erneut prüfen",
  recrawl_preview_page_btn_tooltip: "Erneutes Crawlen der Seite durch Siteimprove",
  recrawl_live_page_btn_text: "Erneut prüfen",
  recrawl_live_page_btn_tooltip: "Sitimprove die Live Seite erneut überprüfen lassen",
  siteimprove_show_more: "Mehr anzeigen",
});
